"""Add refresh token table

Revision ID: 81a7f607eff1
Revises: 79f9dc2ce4f0
Create Date: 2025-05-27 06:19:54.984574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81a7f607eff1'
down_revision: Union[str, None] = '79f9dc2ce4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_email_key', 'clients', type_='unique')
    op.drop_constraint('clients_username_key', 'clients', type_='unique')
    op.add_column('device_firmware_history', sa.Column('update_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_device_firmware_history_device_id'), 'device_firmware_history', ['device_id'], unique=False)
    op.create_foreign_key(None, 'device_firmware_history', 'firmware_updates', ['update_id'], ['id'], ondelete='SET NULL')
    op.drop_column('device_firmware_history', 'update_method')
    op.drop_column('device_firmware_history', 'success')
    op.drop_column('device_firmware_history', 'notes')
    op.drop_index('ix_firmware_updates_created_at', table_name='firmware_updates')
    op.alter_column('notification_recipients', 'notification_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notification_recipients', 'client_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('idx_notification_recipient_status', table_name='notification_recipients')
    op.drop_index('idx_notification_recipients_client', table_name='notification_recipients')
    op.drop_index('idx_notification_recipients_notification', table_name='notification_recipients')
    op.create_index(op.f('ix_notification_recipients_client_id'), 'notification_recipients', ['client_id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_id'), 'notification_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_notification_id'), 'notification_recipients', ['notification_id'], unique=False)
    op.drop_column('notification_recipients', 'status_message')
    op.drop_column('notification_recipients', 'delivery_status')
    op.drop_column('notification_recipients', 'updated_at')
    op.drop_index('idx_notifications_created_priority', table_name='notifications')
    op.drop_index('idx_notifications_target', table_name='notifications')
    op.drop_index('ix_tokens_token', table_name='tokens')
    op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    op.create_index('ix_tokens_token', 'tokens', ['token'], unique=True)
    op.create_index('idx_notifications_target', 'notifications', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_notifications_created_priority', 'notifications', ['created_at', 'priority'], unique=False)
    op.add_column('notification_recipients', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('notification_recipients', sa.Column('delivery_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('notification_recipients', sa.Column('status_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_notification_recipients_notification_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_client_id'), table_name='notification_recipients')
    op.create_index('idx_notification_recipients_notification', 'notification_recipients', ['notification_id'], unique=False)
    op.create_index('idx_notification_recipients_client', 'notification_recipients', ['client_id'], unique=False)
    op.create_index('idx_notification_recipient_status', 'notification_recipients', ['is_delivered', 'is_read'], unique=False)
    op.alter_column('notification_recipients', 'client_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('notification_recipients', 'notification_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_firmware_updates_created_at', 'firmware_updates', ['created_at'], unique=False)
    op.add_column('device_firmware_history', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('device_firmware_history', sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('device_firmware_history', sa.Column('update_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device_firmware_history', type_='foreignkey')
    op.drop_index(op.f('ix_device_firmware_history_device_id'), table_name='device_firmware_history')
    op.drop_column('device_firmware_history', 'update_id')
    op.create_unique_constraint('clients_username_key', 'clients', ['username'])
    op.create_unique_constraint('clients_email_key', 'clients', ['email'])
    # ### end Alembic commands ###
